/**
 * DCP-AI v2.0 Cross-Language Interoperability Tests
 *
 * Verifies golden vectors generated by the TypeScript SDK can be verified
 * locally: kid derivation, canonicalization, domain-separated messages,
 * Ed25519 signatures, composite (Ed25519 + ML-DSA-65) signatures, stripping
 * attack resistance, domain separation, session splicing detection, and
 * NIST KAT conformance.
 *
 * The same interop_vectors.json is consumed by Python, Go, and Rust SDKs
 * to form the 4×4 cross-language verification matrix.
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { readFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

import { Ed25519Provider } from '../providers/ed25519.js';
import { MlDsa65Provider } from '../providers/ml-dsa-65.js';
import { AlgorithmRegistry } from '../core/crypto-registry.js';
import { canonicalizeV2 } from '../core/canonicalize.js';
import { DCP_CONTEXTS, domainSeparatedMessage } from '../core/domain-separation.js';
import {
  compositeSign,
  compositeVerify,
} from '../core/composite-ops.js';
import type { CompositeKeyPair } from '../core/composite-ops.js';
import type { CompositeSignature } from '../core/composite-sig.js';
import { deriveKid } from '../core/crypto-provider.js';
import { sha256Hex, sha3_256Hex } from '../core/dual-hash.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const VECTORS_PATH = resolve(__dirname, '../../../../tests/interop/v2/interop_vectors.json');

let V: any;
let registry: AlgorithmRegistry;
let ed25519: Ed25519Provider;
let mlDsa65: MlDsa65Provider;

beforeAll(() => {
  V = JSON.parse(readFileSync(VECTORS_PATH, 'utf-8'));
  registry = new AlgorithmRegistry();
  ed25519 = new Ed25519Provider();
  mlDsa65 = new MlDsa65Provider();
  registry.registerSigner(ed25519);
  registry.registerSigner(mlDsa65);
});

function toHex(data: Uint8Array): string {
  return Buffer.from(data).toString('hex');
}

// ---------------------------------------------------------------------------
// 1. Kid Derivation Agreement
// ---------------------------------------------------------------------------

describe('Kid Derivation (cross-SDK agreement)', () => {
  it('Ed25519 kid matches expected', () => {
    const { alg, public_key_b64, expected_kid } = V.kid_derivation.ed25519;
    const pkBytes = new Uint8Array(Buffer.from(public_key_b64, 'base64'));
    const kid = deriveKid(alg, pkBytes);
    expect(kid).toBe(expected_kid);
  });

  it('ML-DSA-65 kid matches expected', () => {
    const { alg, public_key_b64, expected_kid } = V.kid_derivation.ml_dsa_65;
    const pkBytes = new Uint8Array(Buffer.from(public_key_b64, 'base64'));
    const kid = deriveKid(alg, pkBytes);
    expect(kid).toBe(expected_kid);
  });
});

// ---------------------------------------------------------------------------
// 2. Canonicalization Agreement
// ---------------------------------------------------------------------------

describe('Canonicalization (cross-SDK agreement)', () => {
  for (const name of ['agent_passport', 'intent', 'audit_event']) {
    it(`${name} canonical form matches`, () => {
      const { input, expected_canonical } = V.canonicalization[name];
      expect(canonicalizeV2(input)).toBe(expected_canonical);
    });
  }
});

// ---------------------------------------------------------------------------
// 3. Payload Hash Agreement
// ---------------------------------------------------------------------------

describe('Payload Hashes (cross-SDK agreement)', () => {
  for (const name of ['agent_passport', 'intent', 'audit_event']) {
    it(`${name} SHA-256 hash matches`, () => {
      const canonical = V.canonicalization[name].expected_canonical;
      const bytes = new TextEncoder().encode(canonical);
      expect(sha256Hex(bytes)).toBe(V.payload_hashes[name].sha256);
    });

    it(`${name} SHA3-256 hash matches`, () => {
      const canonical = V.canonicalization[name].expected_canonical;
      const bytes = new TextEncoder().encode(canonical);
      expect(sha3_256Hex(bytes)).toBe(V.payload_hashes[name].sha3_256);
    });
  }
});

// ---------------------------------------------------------------------------
// 4. Domain-Separated Message Agreement
// ---------------------------------------------------------------------------

describe('Domain-Separated Messages (cross-SDK agreement)', () => {
  it('all contexts produce distinct DSMs for the same payload', () => {
    const payloadBytes = new TextEncoder().encode(
      V.domain_separation_all_contexts.payload_canonical,
    );
    const dsmHexes = new Set<string>();
    for (const [ctxName, ctxValue] of Object.entries(DCP_CONTEXTS)) {
      const dsm = domainSeparatedMessage(ctxValue as string, payloadBytes);
      const hex = toHex(dsm);
      expect(hex).toBe(V.domain_separation_all_contexts.dsm_hex[ctxName]);
      dsmHexes.add(hex);
    }
    expect(dsmHexes.size).toBe(Object.keys(DCP_CONTEXTS).length);
  });

  for (const dsmName of ['passport_dsm', 'intent_dsm', 'audit_dsm']) {
    it(`${dsmName} matches expected hex`, () => {
      expect(V.domain_separated_messages[dsmName]).toBeTruthy();
    });
  }
});

// ---------------------------------------------------------------------------
// 5. Ed25519 Signature Verification
// ---------------------------------------------------------------------------

describe('Ed25519 Signature Verification (interop)', () => {
  const sigNames = ['passport_ed25519', 'intent_ed25519', 'audit_ed25519'];

  for (const sigName of sigNames) {
    it(`verifies ${sigName}`, async () => {
      const entry = V.ed25519_signatures[sigName];
      const canonical = V.canonicalization[entry.payload_key].expected_canonical;
      const payloadBytes = new TextEncoder().encode(canonical);
      const dsm = domainSeparatedMessage(entry.context, payloadBytes);
      const sigBytes = new Uint8Array(Buffer.from(entry.sig_b64, 'base64'));
      const pubKeyB64 = V.test_keys.ed25519.public_key_b64;
      const valid = await ed25519.verify(dsm, sigBytes, pubKeyB64);
      expect(valid).toBe(true);
    });
  }

  it('Ed25519 signature with wrong key fails', async () => {
    const entry = V.ed25519_signatures.passport_ed25519;
    const canonical = V.canonicalization[entry.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const dsm = domainSeparatedMessage(entry.context, payloadBytes);
    const sigBytes = new Uint8Array(Buffer.from(entry.sig_b64, 'base64'));
    const wrongKp = await ed25519.generateKeypair();
    const valid = await ed25519.verify(dsm, sigBytes, wrongKp.publicKeyB64);
    expect(valid).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 6. Composite Signature Verification (Ed25519 + ML-DSA-65)
// ---------------------------------------------------------------------------

describe('Composite Signature Verification (interop)', () => {
  const compNames = ['passport_composite', 'intent_composite', 'audit_composite'];

  for (const compName of compNames) {
    it(`verifies ${compName}`, async () => {
      const entry = V.composite_signatures[compName];
      const canonical = V.canonicalization[entry.payload_key].expected_canonical;
      const payloadBytes = new TextEncoder().encode(canonical);
      const result = await compositeVerify(
        registry,
        entry.context,
        payloadBytes,
        entry.composite_sig as CompositeSignature,
        V.test_keys.ed25519.public_key_b64,
        V.test_keys.ml_dsa_65.public_key_b64,
      );
      expect(result.valid).toBe(true);
      expect(result.classical_valid).toBe(true);
      expect(result.pq_valid).toBe(true);
    });
  }
});

// ---------------------------------------------------------------------------
// 7. Classical-Only Signature Verification
// ---------------------------------------------------------------------------

describe('Classical-Only Composite Signature (interop)', () => {
  it('verifies classical-only intent', async () => {
    const entry = V.classical_only_signatures.intent_classical_only;
    const canonical = V.canonicalization[entry.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const result = await compositeVerify(
      registry,
      entry.context,
      payloadBytes,
      entry.composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
    );
    expect(result.valid).toBe(true);
    expect(result.classical_valid).toBe(true);
    expect(result.pq_valid).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 8. Stripping Attack Tests
// ---------------------------------------------------------------------------

describe('Stripping Attack Resistance (interop)', () => {
  it('PQ removal with pq_over_classical binding fails', async () => {
    const av = V.attack_vectors.stripping_pq_removal;
    const canonical = V.canonicalization[av.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const result = await compositeVerify(
      registry,
      av.context,
      payloadBytes,
      av.composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
      V.test_keys.ml_dsa_65.public_key_b64,
    );
    expect(result.valid).toBe(false);
  });

  it('PQ removal with binding downgrade to classical_only — classical valid but PQ missing', async () => {
    const av = V.attack_vectors.stripping_pq_with_downgrade;
    const canonical = V.canonicalization[av.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const result = await compositeVerify(
      registry,
      av.context,
      payloadBytes,
      av.composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
    );
    expect(result.classical_valid).toBe(true);
    expect(result.pq_valid).toBe(false);
  });

  it('tampered classical signature breaks both verifications', async () => {
    const av = V.attack_vectors.tampered_classical_sig;
    const canonical = V.canonicalization[av.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const result = await compositeVerify(
      registry,
      av.context,
      payloadBytes,
      av.composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
      V.test_keys.ml_dsa_65.public_key_b64,
    );
    expect(result.valid).toBe(false);
    expect(result.classical_valid).toBe(false);
    expect(result.pq_valid).toBe(false);
  });

  it('tampered PQ signature fails overall verification', async () => {
    const av = V.attack_vectors.tampered_pq_sig;
    const canonical = V.canonicalization[av.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const result = await compositeVerify(
      registry,
      av.context,
      payloadBytes,
      av.composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
      V.test_keys.ml_dsa_65.public_key_b64,
    );
    expect(result.valid).toBe(false);
    expect(result.pq_valid).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 9. Cross-Context Replay (Domain Separation)
// ---------------------------------------------------------------------------

describe('Cross-Context Replay Prevention (interop)', () => {
  it('Intent signature fails under AuditEvent context', async () => {
    const av = V.attack_vectors.cross_context_replay;
    const canonical = V.canonicalization[av.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const result = await compositeVerify(
      registry,
      av.verify_context,
      payloadBytes,
      av.composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
      V.test_keys.ml_dsa_65.public_key_b64,
    );
    expect(result.valid).toBe(false);
  });

  it('same payload signed under Intent verifies under Intent', async () => {
    const av = V.attack_vectors.cross_context_replay;
    const canonical = V.canonicalization[av.payload_key].expected_canonical;
    const payloadBytes = new TextEncoder().encode(canonical);
    const result = await compositeVerify(
      registry,
      av.sign_context,
      payloadBytes,
      av.composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
      V.test_keys.ml_dsa_65.public_key_b64,
    );
    expect(result.valid).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// 10. Session Splicing Detection
// ---------------------------------------------------------------------------

describe('Session Splicing Detection (interop)', () => {
  it('passport from session A has different nonce than intent from session B', () => {
    const sA = V.session_splicing.session_a;
    const sB = V.session_splicing.session_b;
    expect(sA.nonce).not.toBe(sB.nonce);
    expect(sA.passport.session_nonce).toBe(sA.nonce);
    expect(sB.intent.session_nonce).toBe(sB.nonce);
    expect(sA.passport.session_nonce).not.toBe(sB.intent.session_nonce);
  });

  it('passport signature from session A verifies independently', async () => {
    const sA = V.session_splicing.session_a;
    const payloadBytes = new TextEncoder().encode(sA.passport_canonical);
    const result = await compositeVerify(
      registry,
      DCP_CONTEXTS.AgentPassport,
      payloadBytes,
      sA.passport_composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
      V.test_keys.ml_dsa_65.public_key_b64,
    );
    expect(result.valid).toBe(true);
  });

  it('intent signature from session B verifies independently', async () => {
    const sB = V.session_splicing.session_b;
    const payloadBytes = new TextEncoder().encode(sB.intent_canonical);
    const result = await compositeVerify(
      registry,
      DCP_CONTEXTS.Intent,
      payloadBytes,
      sB.intent_composite_sig as CompositeSignature,
      V.test_keys.ed25519.public_key_b64,
      V.test_keys.ml_dsa_65.public_key_b64,
    );
    expect(result.valid).toBe(true);
  });

  it('bundle verification MUST detect nonce mismatch (application-level check)', () => {
    const sA = V.session_splicing.session_a;
    const sB = V.session_splicing.session_b;
    const passportNonce = sA.passport.session_nonce;
    const intentNonce = sB.intent.session_nonce;
    const noncesMatch = passportNonce === intentNonce;
    expect(noncesMatch).toBe(false);
  });
});

// ---------------------------------------------------------------------------
// 11. Self-Sign and Self-Verify (local round-trip)
// ---------------------------------------------------------------------------

describe('Local Round-Trip (sign + verify)', () => {
  it('Ed25519 + ML-DSA-65 composite round-trip', async () => {
    const edKp = await ed25519.generateKeypair();
    const pqKp = await mlDsa65.generateKeypair();
    const localKeys: CompositeKeyPair = {
      classical: {
        kid: edKp.kid,
        alg: 'ed25519',
        secretKeyB64: edKp.secretKeyB64,
        publicKeyB64: edKp.publicKeyB64,
      },
      pq: {
        kid: pqKp.kid,
        alg: 'ml-dsa-65',
        secretKeyB64: pqKp.secretKeyB64,
        publicKeyB64: pqKp.publicKeyB64,
      },
    };
    const payload = canonicalizeV2({ test: 'round-trip', ts: 1234567890 });
    const payloadBytes = new TextEncoder().encode(payload);
    const sig = await compositeSign(
      registry,
      DCP_CONTEXTS.AgentPassport,
      payloadBytes,
      localKeys,
    );
    const result = await compositeVerify(
      registry,
      DCP_CONTEXTS.AgentPassport,
      payloadBytes,
      sig,
      edKp.publicKeyB64,
      pqKp.publicKeyB64,
    );
    expect(result.valid).toBe(true);
    expect(result.classical_valid).toBe(true);
    expect(result.pq_valid).toBe(true);
  });
});

// ---------------------------------------------------------------------------
// 12. Composite Binding Direction Enforcement
// ---------------------------------------------------------------------------

describe('Composite Binding Direction', () => {
  it('PQ signature covers classical signature (binding integrity)', async () => {
    const edKp = await ed25519.generateKeypair();
    const pqKp = await mlDsa65.generateKeypair();
    const localKeys: CompositeKeyPair = {
      classical: {
        kid: edKp.kid,
        alg: 'ed25519',
        secretKeyB64: edKp.secretKeyB64,
        publicKeyB64: edKp.publicKeyB64,
      },
      pq: {
        kid: pqKp.kid,
        alg: 'ml-dsa-65',
        secretKeyB64: pqKp.secretKeyB64,
        publicKeyB64: pqKp.publicKeyB64,
      },
    };
    const payload = canonicalizeV2({ binding: 'test' });
    const payloadBytes = new TextEncoder().encode(payload);
    const sig = await compositeSign(
      registry,
      DCP_CONTEXTS.Bundle,
      payloadBytes,
      localKeys,
    );

    expect(sig.binding).toBe('pq_over_classical');

    const swapped: CompositeSignature = {
      classical: { ...sig.classical, sig_b64: sig.pq!.sig_b64 },
      pq: { ...sig.pq!, sig_b64: sig.classical.sig_b64 },
      binding: 'pq_over_classical',
    };
    try {
      const result = await compositeVerify(
        registry,
        DCP_CONTEXTS.Bundle,
        payloadBytes,
        swapped,
        edKp.publicKeyB64,
        pqKp.publicKeyB64,
      );
      expect(result.valid).toBe(false);
    } catch {
      // Size mismatch errors (e.g. 3309B PQ sig in 64B Ed25519 slot) are expected
    }
  });
});

describe('canonicalization edge cases (dcp-jcs-v1 profile)', () => {
  type EdgeVec = {
    name: string;
    input?: unknown;
    input_json?: string;
    canonical?: string;
    expects_error?: boolean;
  };

  it('all vectors match the dcp-jcs-v1 profile', () => {
    const edge = (V as any).canonicalization.edge_cases.vectors as EdgeVec[];
    for (const vec of edge) {
      const payload =
        'input' in vec && vec.input !== undefined
          ? vec.input
          : JSON.parse(vec.input_json!);

      if (vec.expects_error) {
        expect(() => canonicalizeV2(payload), `${vec.name} should throw`).toThrow();
      } else {
        expect(canonicalizeV2(payload), `${vec.name} canonical mismatch`).toBe(
          vec.canonical,
        );
      }
    }
  });
});
