/**
 * Inline DCP v1 JSON Schemas for self-contained validation.
 * These are the canonical schemas from the DCP specification.
 */

export const SCHEMAS: Record<string, any> = {
  human_binding_record: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/human_binding_record.schema.json',
    title: 'HumanBindingRecord',
    type: 'object',
    additionalProperties: false,
    required: ['dcp_version','human_id','legal_name','entity_type','jurisdiction','liability_mode','override_rights','issued_at','expires_at','signature'],
    properties: {
      dcp_version: { type: 'string', pattern: '^1\\.0$' },
      human_id: { type: 'string', minLength: 6 },
      legal_name: { type: 'string', minLength: 1 },
      entity_type: { type: 'string', enum: ['natural_person','organization'] },
      jurisdiction: { type: 'string', minLength: 2, maxLength: 10 },
      liability_mode: { type: 'string', enum: ['owner_responsible'] },
      override_rights: { type: 'boolean' },
      issued_at: { type: 'string', format: 'date-time' },
      expires_at: { type: ['string','null'], format: 'date-time' },
      contact: { type: ['string','null'] },
      signature: { type: 'string', minLength: 8 },
    },
  },
  agent_passport: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/agent_passport.schema.json',
    title: 'AgentPassport',
    type: 'object',
    additionalProperties: false,
    required: ['dcp_version','agent_id','public_key','human_binding_reference','created_at','status','signature'],
    properties: {
      dcp_version: { type: 'string', pattern: '^1\\.0$' },
      agent_id: { type: 'string', minLength: 6 },
      public_key: { type: 'string', minLength: 8 },
      human_binding_reference: { type: 'string', minLength: 6 },
      capabilities: { type: 'array', items: { type: 'string', enum: ['browse','api_call','email','calendar','payments','crm','file_write','code_exec'] }, uniqueItems: true },
      risk_tier: { type: 'string', enum: ['low','medium','high'] },
      created_at: { type: 'string', format: 'date-time' },
      status: { type: 'string', enum: ['active','revoked','suspended'] },
      signature: { type: 'string', minLength: 8 },
    },
  },
  intent: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/intent.schema.json',
    title: 'Intent',
    type: 'object',
    additionalProperties: false,
    required: ['dcp_version','intent_id','agent_id','human_id','timestamp','action_type','target','data_classes','estimated_impact'],
    properties: {
      dcp_version: { type: 'string', pattern: '^1\\.0$' },
      intent_id: { type: 'string', minLength: 6 },
      agent_id: { type: 'string', minLength: 6 },
      human_id: { type: 'string', minLength: 6 },
      timestamp: { type: 'string', format: 'date-time' },
      action_type: { type: 'string', enum: ['browse','api_call','send_email','create_calendar_event','initiate_payment','update_crm','write_file','execute_code'] },
      target: {
        type: 'object', additionalProperties: true, required: ['channel'],
        properties: {
          channel: { type: 'string', enum: ['web','api','email','calendar','payments','crm','filesystem','runtime'] },
          to: { type: ['string','null'] },
          domain: { type: ['string','null'] },
          url: { type: ['string','null'] },
        },
      },
      data_classes: { type: 'array', minItems: 1, uniqueItems: true, items: { type: 'string', enum: ['none','contact_info','pii','credentials','financial_data','health_data','children_data','company_confidential'] } },
      estimated_impact: { type: 'string', enum: ['low','medium','high'] },
      requires_consent: { type: ['boolean','null'] },
    },
  },
  policy_decision: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/policy_decision.schema.json',
    title: 'PolicyDecision',
    type: 'object',
    additionalProperties: false,
    required: ['dcp_version','intent_id','decision','risk_score','reasons'],
    properties: {
      dcp_version: { type: 'string', pattern: '^1\\.0$' },
      intent_id: { type: 'string', minLength: 6 },
      decision: { type: 'string', enum: ['approve','escalate','block'] },
      risk_score: { type: 'number', minimum: 0, maximum: 1 },
      reasons: { type: 'array', minItems: 1, items: { type: 'string' } },
      required_confirmation: {
        type: ['object','null'], additionalProperties: false,
        required: ['type'],
        properties: {
          type: { type: 'string', enum: ['human_approve'] },
          fields: { type: 'array', items: { type: 'string' } },
        },
      },
    },
  },
  audit_entry: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/audit_entry.schema.json',
    title: 'AuditEntry',
    type: 'object',
    additionalProperties: false,
    required: ['dcp_version','audit_id','prev_hash','timestamp','agent_id','human_id','intent_id','intent_hash','policy_decision','outcome','evidence'],
    properties: {
      dcp_version: { type: 'string', pattern: '^1\\.0$' },
      audit_id: { type: 'string', minLength: 6 },
      prev_hash: { type: 'string', minLength: 1 },
      timestamp: { type: 'string', format: 'date-time' },
      agent_id: { type: 'string', minLength: 6 },
      human_id: { type: 'string', minLength: 6 },
      intent_id: { type: 'string', minLength: 6 },
      intent_hash: { type: 'string', minLength: 8 },
      policy_decision: { type: 'string', enum: ['approved','escalated','blocked'] },
      outcome: { type: 'string', minLength: 1 },
      evidence: {
        type: 'object', additionalProperties: true,
        properties: {
          tool: { type: ['string','null'] },
          result_ref: { type: ['string','null'] },
        },
      },
    },
  },
  citizenship_bundle: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/citizenship_bundle.schema.json',
    title: 'CitizenshipBundle',
    type: 'object',
    additionalProperties: false,
    required: ['human_binding_record','agent_passport','intent','policy_decision','audit_entries'],
    properties: {
      human_binding_record: { $ref: 'https://dcp-ai.org/schemas/v1/human_binding_record.schema.json' },
      agent_passport: { $ref: 'https://dcp-ai.org/schemas/v1/agent_passport.schema.json' },
      intent: { $ref: 'https://dcp-ai.org/schemas/v1/intent.schema.json' },
      policy_decision: { $ref: 'https://dcp-ai.org/schemas/v1/policy_decision.schema.json' },
      audit_entries: { type: 'array', minItems: 1, items: { $ref: 'https://dcp-ai.org/schemas/v1/audit_entry.schema.json' } },
    },
  },
  signed_bundle: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/signed_bundle.schema.json',
    title: 'SignedBundle',
    type: 'object',
    additionalProperties: false,
    required: ['bundle','signature'],
    properties: {
      bundle: { $ref: 'https://dcp-ai.org/schemas/v1/citizenship_bundle.schema.json' },
      signature: {
        type: 'object', additionalProperties: false,
        required: ['alg','created_at','signer','bundle_hash','sig_b64'],
        properties: {
          alg: { type: 'string', enum: ['ed25519'] },
          created_at: { type: 'string', format: 'date-time' },
          signer: {
            type: 'object', additionalProperties: false,
            required: ['type','id','public_key_b64'],
            properties: {
              type: { type: 'string', enum: ['human','organization'] },
              id: { type: 'string', minLength: 6 },
              public_key_b64: { type: 'string', minLength: 8 },
            },
          },
          bundle_hash: { type: 'string', pattern: '^sha256:[0-9a-f]{64}$' },
          merkle_root: { type: ['string','null'], pattern: '^sha256:[0-9a-f]{64}$' },
          sig_b64: { type: 'string', minLength: 8 },
        },
      },
    },
  },
  revocation_record: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/revocation_record.schema.json',
    title: 'RevocationRecord',
    type: 'object',
    additionalProperties: false,
    required: ['dcp_version','agent_id','human_id','timestamp','reason','signature'],
    properties: {
      dcp_version: { type: 'string', pattern: '^1\\.0$' },
      agent_id: { type: 'string', minLength: 6 },
      human_id: { type: 'string', minLength: 6 },
      timestamp: { type: 'string', format: 'date-time' },
      reason: { type: 'string', minLength: 1 },
      signature: { type: 'string', minLength: 8 },
    },
  },
  human_confirmation: {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://dcp-ai.org/schemas/v1/human_confirmation.schema.json',
    title: 'HumanConfirmation',
    type: 'object',
    additionalProperties: false,
    required: ['dcp_version','intent_id','human_id','timestamp','decision','signature'],
    properties: {
      dcp_version: { type: 'string', pattern: '^1\\.0$' },
      intent_id: { type: 'string', minLength: 6 },
      human_id: { type: 'string', minLength: 6 },
      timestamp: { type: 'string', format: 'date-time' },
      decision: { type: 'string', enum: ['approve','deny'] },
      signature: { type: 'string', minLength: 8 },
    },
  },
};
