"""
DCP-AI v2.0 Cross-Language Interoperability Tests (Python SDK)

Verifies golden vectors generated by the TypeScript SDK. Covers kid
derivation, canonicalization, domain separation, Ed25519 signature
verification, composite (Ed25519 + ML-DSA-65) signature verification,
stripping attack resistance, cross-context replay, and session splicing.

The same interop_vectors.json is consumed by TS, Go, and Rust SDKs
to form the 4×4 cross-language verification matrix.
"""

from __future__ import annotations

import base64
import json
import os
from pathlib import Path

import pytest

from dcp_ai.v2.crypto_provider import derive_kid
from dcp_ai.v2.canonicalize import canonicalize_v2
from dcp_ai.v2.domain_separation import DCP_CONTEXTS, domain_separated_message
from dcp_ai.v2.dual_hash import sha256_hex, sha3_256_hex
from dcp_ai.v2.crypto_registry import AlgorithmRegistry
from dcp_ai.v2.composite_ops import composite_verify, CompositeKeyInfo
from dcp_ai.providers.ed25519_provider import Ed25519Provider

VECTORS_PATH = Path(__file__).resolve().parent.parent.parent.parent / "tests" / "interop" / "v2" / "interop_vectors.json"


@pytest.fixture(scope="module")
def V():
    with open(VECTORS_PATH) as f:
        return json.load(f)


@pytest.fixture(scope="module")
def registry():
    r = AlgorithmRegistry()
    r.register_signer(Ed25519Provider())
    try:
        from dcp_ai.providers.ml_dsa_65_provider import MlDsa65Provider
        r.register_signer(MlDsa65Provider())
    except ImportError:
        pass
    return r


def _has_pq(registry: AlgorithmRegistry) -> bool:
    return registry.has_signer("ml-dsa-65")


# ---------------------------------------------------------------------------
# 1. Kid Derivation Agreement
# ---------------------------------------------------------------------------


class TestKidDerivation:
    def test_ed25519_kid(self, V):
        kd = V["kid_derivation"]["ed25519"]
        pk_bytes = base64.b64decode(kd["public_key_b64"])
        kid = derive_kid(kd["alg"], pk_bytes)
        assert kid == kd["expected_kid"]

    def test_ml_dsa_65_kid(self, V):
        kd = V["kid_derivation"]["ml_dsa_65"]
        pk_bytes = base64.b64decode(kd["public_key_b64"])
        kid = derive_kid(kd["alg"], pk_bytes)
        assert kid == kd["expected_kid"]


# ---------------------------------------------------------------------------
# 2. Canonicalization Agreement
# ---------------------------------------------------------------------------


class TestCanonicalization:
    @pytest.mark.parametrize("name", ["agent_passport", "intent", "audit_event"])
    def test_canonical_form(self, V, name):
        entry = V["canonicalization"][name]
        assert canonicalize_v2(entry["input"]) == entry["expected_canonical"]


# ---------------------------------------------------------------------------
# 3. Payload Hash Agreement
# ---------------------------------------------------------------------------


class TestPayloadHashes:
    @pytest.mark.parametrize("name", ["agent_passport", "intent", "audit_event"])
    def test_sha256(self, V, name):
        canonical = V["canonicalization"][name]["expected_canonical"]
        assert sha256_hex(canonical.encode("utf-8")) == V["payload_hashes"][name]["sha256"]

    @pytest.mark.parametrize("name", ["agent_passport", "intent", "audit_event"])
    def test_sha3_256(self, V, name):
        canonical = V["canonicalization"][name]["expected_canonical"]
        assert sha3_256_hex(canonical.encode("utf-8")) == V["payload_hashes"][name]["sha3_256"]


# ---------------------------------------------------------------------------
# 4. Domain-Separated Messages Agreement
# ---------------------------------------------------------------------------


class TestDomainSeparation:
    def test_all_contexts_distinct(self, V):
        payload = V["domain_separation_all_contexts"]["payload_canonical"].encode("utf-8")
        dsm_set = set()
        for ctx_name, ctx_val in DCP_CONTEXTS.items():
            dsm = domain_separated_message(ctx_val, payload)
            hex_val = dsm.hex()
            expected = V["domain_separation_all_contexts"]["dsm_hex"][ctx_name]
            assert hex_val == expected, f"DSM mismatch for {ctx_name}"
            dsm_set.add(hex_val)
        assert len(dsm_set) == len(DCP_CONTEXTS)


# ---------------------------------------------------------------------------
# 5. Ed25519 Signature Verification
# ---------------------------------------------------------------------------


class TestEd25519Signatures:
    @pytest.mark.asyncio
    @pytest.mark.parametrize("sig_name", ["passport_ed25519", "intent_ed25519", "audit_ed25519"])
    async def test_verify(self, V, registry, sig_name):
        entry = V["ed25519_signatures"][sig_name]
        canonical = V["canonicalization"][entry["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        dsm = domain_separated_message(entry["context"], payload_bytes)
        sig_bytes = base64.b64decode(entry["sig_b64"])
        pub_key_b64 = V["test_keys"]["ed25519"]["public_key_b64"]
        ed = Ed25519Provider()
        valid = await ed.verify(dsm, sig_bytes, pub_key_b64)
        assert valid is True

    @pytest.mark.asyncio
    async def test_wrong_key_fails(self, V, registry):
        entry = V["ed25519_signatures"]["passport_ed25519"]
        canonical = V["canonicalization"][entry["payload_key"]]["expected_canonical"]
        dsm = domain_separated_message(entry["context"], canonical.encode("utf-8"))
        sig_bytes = base64.b64decode(entry["sig_b64"])
        ed = Ed25519Provider()
        wrong_kp = await ed.generate_keypair()
        valid = await ed.verify(dsm, sig_bytes, wrong_kp["public_key_b64"])
        assert valid is False


# ---------------------------------------------------------------------------
# 6. Composite Signature Verification
# ---------------------------------------------------------------------------


class TestCompositeSignatures:
    @pytest.mark.asyncio
    @pytest.mark.parametrize("comp_name", ["passport_composite", "intent_composite", "audit_composite"])
    async def test_verify(self, V, registry, comp_name):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        entry = V["composite_signatures"][comp_name]
        canonical = V["canonicalization"][entry["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            entry["context"],
            payload_bytes,
            entry["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is True
        assert result.classical_valid is True
        assert result.pq_valid is True


# ---------------------------------------------------------------------------
# 7. Classical-Only Signature Verification
# ---------------------------------------------------------------------------


class TestClassicalOnly:
    @pytest.mark.asyncio
    async def test_verify_classical_only(self, V, registry):
        entry = V["classical_only_signatures"]["intent_classical_only"]
        canonical = V["canonicalization"][entry["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            entry["context"],
            payload_bytes,
            entry["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
        )
        assert result.valid is True
        assert result.classical_valid is True
        assert result.pq_valid is False


# ---------------------------------------------------------------------------
# 8. Stripping Attack Resistance
# ---------------------------------------------------------------------------


class TestStrippingAttacks:
    @pytest.mark.asyncio
    async def test_pq_removal_fails(self, V, registry):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        av = V["attack_vectors"]["stripping_pq_removal"]
        canonical = V["canonicalization"][av["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            av["context"],
            payload_bytes,
            av["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is False

    @pytest.mark.asyncio
    async def test_pq_removal_with_downgrade(self, V, registry):
        av = V["attack_vectors"]["stripping_pq_with_downgrade"]
        canonical = V["canonicalization"][av["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            av["context"],
            payload_bytes,
            av["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
        )
        assert result.classical_valid is True
        assert result.pq_valid is False

    @pytest.mark.asyncio
    async def test_tampered_classical(self, V, registry):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        av = V["attack_vectors"]["tampered_classical_sig"]
        canonical = V["canonicalization"][av["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            av["context"],
            payload_bytes,
            av["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is False
        assert result.classical_valid is False

    @pytest.mark.asyncio
    async def test_tampered_pq(self, V, registry):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        av = V["attack_vectors"]["tampered_pq_sig"]
        canonical = V["canonicalization"][av["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            av["context"],
            payload_bytes,
            av["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is False
        assert result.pq_valid is False


# ---------------------------------------------------------------------------
# 9. Cross-Context Replay Prevention
# ---------------------------------------------------------------------------


class TestCrossContextReplay:
    @pytest.mark.asyncio
    async def test_intent_sig_fails_under_audit(self, V, registry):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        av = V["attack_vectors"]["cross_context_replay"]
        canonical = V["canonicalization"][av["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            av["verify_context"],
            payload_bytes,
            av["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is False

    @pytest.mark.asyncio
    async def test_intent_sig_succeeds_under_intent(self, V, registry):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        av = V["attack_vectors"]["cross_context_replay"]
        canonical = V["canonicalization"][av["payload_key"]]["expected_canonical"]
        payload_bytes = canonical.encode("utf-8")
        result = await composite_verify(
            registry,
            av["sign_context"],
            payload_bytes,
            av["composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is True


# ---------------------------------------------------------------------------
# 10. Session Splicing Detection
# ---------------------------------------------------------------------------


class TestSessionSplicing:
    def test_nonces_differ(self, V):
        sa = V["session_splicing"]["session_a"]
        sb = V["session_splicing"]["session_b"]
        assert sa["nonce"] != sb["nonce"]
        assert sa["passport"]["session_nonce"] == sa["nonce"]
        assert sb["intent"]["session_nonce"] == sb["nonce"]

    @pytest.mark.asyncio
    async def test_passport_a_verifies(self, V, registry):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        sa = V["session_splicing"]["session_a"]
        payload_bytes = sa["passport_canonical"].encode("utf-8")
        result = await composite_verify(
            registry,
            DCP_CONTEXTS["AgentPassport"],
            payload_bytes,
            sa["passport_composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is True

    @pytest.mark.asyncio
    async def test_intent_b_verifies(self, V, registry):
        if not _has_pq(registry):
            pytest.skip("ML-DSA-65 provider not available")
        sb = V["session_splicing"]["session_b"]
        payload_bytes = sb["intent_canonical"].encode("utf-8")
        result = await composite_verify(
            registry,
            DCP_CONTEXTS["Intent"],
            payload_bytes,
            sb["intent_composite_sig"],
            V["test_keys"]["ed25519"]["public_key_b64"],
            V["test_keys"]["ml_dsa_65"]["public_key_b64"],
        )
        assert result.valid is True

    def test_bundle_nonce_mismatch(self, V):
        """Simulates bundle verification: nonces must match across artifacts."""
        sa = V["session_splicing"]["session_a"]
        sb = V["session_splicing"]["session_b"]
        assert sa["passport"]["session_nonce"] != sb["intent"]["session_nonce"]
